export const Questions = [
    {
      prompt: "Which is of these is not core datatype?",
      optionA: "Lists",
      optionB: "Dictonary",
      optionC: "Tuple",
      optionD: "Class",
      answer: "D",
    },
    {
      prompt: "Which of this is not a programming language?",
      optionA: "Python",
      optionB: "JavaScript",
      optionC: "MC-03",
      optionD: "Java",
      answer: "C",
    },
    {
      prompt: "What does HTML stands for?",
      optionA: "HyperText Markup Language",
      optionB: "Hot Mail",
      optionC: "Hyperlink and TextMarkup Language",
      optionD:"Home tool Markup Language",
      answer: "A",
    },
    {
      prompt: "Which of these is interface between user and Kernel?",
      optionA: "Oracle",
      optionB: "Shell",
      optionC: "Linux",
      optionD:"Window",
      answer: "B",
    },
    {
      prompt: "How many tables may be included with a join?",
      optionA: "One",
      optionB: "Two",
      optionC: "Three",
      optionD:"All of the Above",
      answer: "D",
    },
    {
      prompt: "Which of this is not a javascript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "D",
    },
    {
      prompt: "What is most valued Language?",
      optionA: "C",
      optionB: "C++",
      optionC: "Java",
      optionD: "Swift",
      answer: "C",
    },
    {
      prompt: "Which is a Javascript Library",
      optionA: "React",
      optionB: "Vue",
      optionC: "Angular",
      optionD: "Next.js",
      answer: "A",
    },
    {
      prompt: "What Language is used in Back-end",
      optionA: "Node JS",
      optionB: "Java",
      optionC: "PHP",
      optionD: "Python",
      answer: "B",
    },
  ];
  